[project]
name = "journald-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.23.1",
    "systemd-python>=235",
    "click>=8.2.0"
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
